version: '3'
services:
    bot:
        container_name: discord_bot
        build: .
        restart: always
        environment:
            - GO_DIR=/usr/src/bot/commands/go
            - TZ=America/Winnipeg
