module.exports = {
    DISCORD_ADMIN_ID:                       process.env.DISCORD_ADMIN_ID                        || "",
    DISCORD_BOT_ID:                         process.env.DISCORD_BOT_ID                          || "",
    DISCORD_CLIENT_ID:                      process.env.DISCORD_CLIENT_ID                       || "",
    DISCORD_DUNGEONS_AND_DRAGONS:           process.env.DISCORD_DUNGEONS_AND_DRAGONS            || "",
    DISCORD_GUILD_ID:                       process.env.DISCORD_GUILD_ID                        || "",
    DISCORD_HUBOT_TESTING:                  process.env.DISCORD_HUBOT_TESTING                   || "",
    GOOGLE_SPREADSHEET_ID:                  process.env.GOOGLE_SPREADSHEET_ID                   || "",
    DISCORD_TOKEN:                          process.env.DISCORD_TOKEN                           || "",
    GOOGLE_AUTH_PROVIDER_X509_CERT_URL:     process.env.GOOGLE_AUTH_PROVIDER_X509_CERT_URL      || "",
    GOOGLE_AUTH_URI:                        process.env.GOOGLE_AUTH_URI                         || "",
    GOOGLE_CLIENT_EMAIL:                    process.env.GOOGLE_CLIENT_EMAIL                     || "",
    GOOGLE_CLIENT_ID:                       process.env.GOOGLE_CLIENT_ID                        || "",
    GOOGLE_CLIENT_X509_CERT_URL:            process.env.GOOGLE_CLIENT_X509_CERT_URL             || "",
    GOOGLE_PRIVATE_KEY:                     process.env.GOOGLE_PRIVATE_KEY                      || "",
    GOOGLE_PRIVATE_KEY_ID:                  process.env.GOOGLE_PRIVATE_KEY_ID                   || "",
    GOOGLE_PROJECT_ID:                      process.env.GOOGLE_PROJECT_ID                       || "",
    GOOGLE_TOKEN_URI:                       process.env.GOOGLE_TOKEN_URI                        || "",
    GOOGLE_TYPE:                            process.env.GOOGLE_TYPE                             || "",
};